name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Rust components
        run: rustup component add rustfmt && rustup component add clippy
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - name: Install moleculec v0.7.2
        run: CARGO_TARGET_DIR=target/ cargo install moleculec --version 0.7.2
      - name: Copy contracts from prebuild docker images
        run: devtools/fetch-binaries.sh
      - name: Tests
        run: |
          while true
          do
            RUST_LOG=debug RUST_BACKTRACE=1 cargo test --all-targets
          done
      - name: Test TOML serialization
        run: cargo run --bin godwoken -- generate-example-config -o test.toml
